---
title: "car_emissions Co2"
output: pdf_document
date: "2025-03-03"
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
#| label: Reading in data

carData <- read_csv("carData.csv")
```

```{r cars}
#read in data set
Yugo_emissions <- carData |>
  select(day, co2, car, dev) |>
  filter(car == "Yugo") |>
  group_by(day, dev) |>
  summarise(Avg_emission = mean(co2, na.rm = TRUE))

Yugo_Co2 <- ggplot(Yugo_emissions, aes(x = day, y = Avg_emission, colour = dev, group = dev)) +
  geom_line(size = 1) +  # Line color and thickness
  geom_point(size = 2) +  # Add points for clarity
  labs(title = "Yugo Co2 Emissions", x = "Day", y = "Co2 Emissions") +
  theme_minimal()

Bentley_emissions <- carData |>
  select(day, co2, car, dev) |>
  filter(car == "Bentley") |>
  group_by(day, dev) |>
  summarise(Avg_emission = mean(co2, na.rm = TRUE))

Bentley_Co2 <- ggplot(Bentley_emissions, aes(x = day, y = Avg_emission, colour = dev, group = dev)) +
  geom_line(size = 1) +  # Line color and thickness
  geom_point(size = 2) +  # Add points for clarity
  labs(title = "Bentley Co2 Emissions", x = "Day", y = "Co2 Emissions") +
  theme_minimal()

Yugo_Co2
Bentley_Co2
  
```
