---
title: "Yugo and Bentley Hydrocarbon (HC) Emissions"
output: pdf_document
date: "2025-03-04"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
#| label: Reading in data
#| message: False

carData <- read_csv("carData.csv")
```


```{r}
#| label: Yugo Hydrocarbon Emissions
#| message: false

Yugo_hc_emissions <- carData |>
  select(day, hc, car, dev) |>
  mutate(dev = ifelse(dev > 0, "Yes", "No")) |> #Ensuring that device is either T or F
  filter(car == "Yugo") |>
  group_by(dev, day) |> 
  summarise(avg_emission = mean(hc, na.rm = TRUE))

Yugo_hc_plot <- ggplot(Yugo_hc_emissions, aes(x = day, y = avg_emission, colour = dev, group = dev)) +
  geom_line(linewidth = 1.5) + 
  geom_point(size = 3) + 
  scale_color_manual(values = c("Yes" = "orange", "No" = "blue")) + 
  labs(
    title = "Yugo Hydrocarbon Emissions Over Time",
    x = "Day of Observation",
    y = "Average HC Emissions (ppm)",
    colour = "Device Installed?"
  ) +
  theme_light(base_size = 14) 
```

\newpage
```{r, fig.cap = Yugo_hc_Caption}
#| echo: false

Yugo_hc_Caption <- "The graph shows that Yugos with the device had highly variable hydrocarbon emissions, which ranged between a low of 1.1 ppm on day 10 to a high of 25.9 ppm on the 7th day. The Yugos without the device had relatively more stable emissions measurements; however, there were only 4 recorded observations, limiting our ability to make comparisons between the cars that did and did not have the device installed."

Yugo_hc_plot
```
\newpage
```{r}
#| label: Bentley Hydrocarbon Emissions
#| message: false

Bentley_hc_emissions <- carData |>
  select(day, hc, car, dev) |>
  mutate(dev = ifelse(dev > 0, "Yes", "No")) |> #Ensuring that device is either T or F
  filter(car == "Bentley") |>
  group_by(dev, day) |> 
  summarise(avg_emission = mean(hc, na.rm = TRUE))

Bentley_hc_plot <- ggplot(Bentley_hc_emissions, aes(x = day, y = avg_emission, colour = dev, group = dev)) +
  geom_line(linewidth = 1.5) + 
  geom_point(size = 3) + 
  scale_color_manual(values = c("Yes" = "orange", "No" = "blue")) + 
  labs(
    title = "Bentley Hydrocarbon Emissions Over Time",
    x = "Day of Observation",
    y = "Average HC Emissions (ppm)",
    colour = "Device Installed?"
  ) +
  theme_light(base_size = 14) 
```
\newpage
```{r, fig.cap= Bentley_hc_Caption}
#| echo: false

Bentley_hc_Caption <- "The graph shows that after the device was installed, the Bentley's average hydrocarbon emissions dropped substantially. Prior to the device installation, the mean hydrocarbon emissions ranged from 4.09 ppm to 7.3 ppm. Emissions reached a maximum (10.7 ppm) on the day the device was installed, but dropped to 4.9 ppm the next day. Thereafter, average Bentley hydrocarbon emissions were consistently below 4.0 ppm."

Bentley_hc_plot
```

